### ISSUE TITLE
显示 ClientException: ffmpeg was not found

### ISSUE THREAD

**Issue by rnoneon29** [vinelin/discord-bot-163-netease-meusic#1]
跟着步骤做了 但是.play 歌曲的时候 他不会播放歌曲 
显示 ClientException: ffmpeg was not found

**Comment by vinelin** [comment]
刚刚测试了一下 播放没有问题 我的python3版本是 3.6.12
应该是需要您安装一下相应系统的必须库

discord.py 官方是使用说明是这样说的 

Please note that on Linux installing voice you must install the following packages via your favourite package manager (e.g. apt, dnf, etc) before running the above commands:

libffi-dev (or libffi-devel on some systems)
python-dev (e.g. python3.6-dev for Python 3.6)

**Comment by rnoneon29** [comment]
电脑没有 ffmpeg
现在 解决了 谢谢您
